[Rainmeter]
Update=1000
AccurateText=1
BackgroundMode=2
SolidColor=0,0,0,0
OnRefreshAction=[!ActivateConfig "Clock" "Clock.ini"][!ActivateConfig "Status" "Status.ini"]

[Metadata]
Name=MD3 Layout
Author=fengcwf
Information=Top-level layout that composes multiple components.

[Variables]
ImgPath=#@#\Images\
LayoutW=900
LayoutH=300

[MeterBackground]
Meter=Image
ImageName=#ImgPath#ui.png
W=#LayoutW#
H=#LayoutH#
X=0
Y=0
PreserveAspectRatio=1

; Tips: Use !ActivateConfig to load other components dynamically if desired.
